namespace ProductionReadySetup.Caching.Api.Options
{
    /// <summary>
    /// Strongly-typed options for cache behavior and key construction.
    ///
    /// WHY SEPARATE FROM RedisOptions:
    ///   RedisOptions = HOW to connect to Redis (infrastructure concern).
    ///   CacheOptions = HOW to use the cache (application behavior concern).
    ///   Keeping them separate lets you swap Redis config without touching
    ///   cache TTL/prefix logic and vice versa.
    ///
    /// BOUND TO: appsettings.json → "Cache" section
    /// </summary>
    public sealed class CacheOptions
    {
        public const string SectionName = "Cache";

        /// <summary>
        /// Top-level prefix for all cache keys generated by this application.
        /// Maps to the application/service name.
        /// Final key format: "{AppPrefix}:{Environment}:{resource}:{id}"
        /// Example:          "caching-api:production:orders:123"
        /// </summary>
        public string AppPrefix { get; init; } = "app";

        /// <summary>
        /// Environment segment in the key.
        /// WHY: Prevents key collision if staging and production
        /// accidentally share a Redis instance (not recommended, but happens).
        /// </summary>
        public string Environment { get; init; } = "development";

        /// <summary>
        /// Default TTL (Time To Live) for cache entries when no explicit TTL is provided.
        /// WHY 5 minutes: Safe default for most read-heavy scenarios.
        /// Override per call for data with different freshness requirements.
        /// </summary>
        public TimeSpan DefaultTtl { get; init; } = TimeSpan.FromMinutes(5);

        /// <summary>
        /// Maximum jitter added to TTL to prevent cache stampede.
        ///
        /// WHAT IS STAMPEDE:
        ///   If 1000 entries all expire at the same second, 1000 requests
        ///   simultaneously hit the database. Jitter spreads expiry across
        ///   a window, smoothing the load.
        ///
        /// HOW: Actual TTL = DefaultTtl + Random(0, MaxJitter)
        /// WHY 30 seconds: Small enough to not affect freshness meaningfully,
        /// large enough to spread expiry across a window.
        /// </summary>
        public TimeSpan MaxJitter { get; init; } = TimeSpan.FromSeconds(30);

        /// <summary>
        /// Whether cache SET failures should throw or be swallowed.
        ///
        /// WHY FALSE (default):
        ///   Cache is a performance optimization, not a source of truth.
        ///   A failed cache write should be logged and ignored — the request
        ///   succeeds by falling back to the source of truth.
        ///   Only set to true if your design REQUIRES cache consistency.
        ///
        /// PITFALL: Setting this to true makes every cache write a
        /// potential request failure. Redis downtime = API downtime.
        /// </summary>
        public bool ThrowOnCacheFailure { get; init; } = false;
    }
}
