namespace ProductionReadySetup.Caching.Api.Options
{
    /// <summary>
    /// Strongly-typed options for cache behavior and key construction.
    ///
    /// WHY SEPARATE FROM RedisOptions:
    ///   RedisOptions = HOW to connect to Redis (infrastructure concern).
    ///   CacheOptions = HOW to use the cache (application behavior concern).
    ///   Keeping them separate lets you swap Redis config without touching
    ///   cache TTL/prefix logic and vice versa.
    ///   
    /// UPDATED IN TRACK 4:
    ///   Added MemoryTtl — controls L1 (in-process memory) expiry.
    ///   L1 TTL must always be shorter than L2 (Redis) TTL.
    ///
    ///   WHY: If L1 TTL >= L2 TTL, memory serves stale data even after
    ///   Redis has expired it. L1 expires first → request falls to L2
    ///   (not DB) → fresh data repopulates L1. Correct degradation path.
    /// 
    /// BOUND TO: appsettings.json → "Cache" section
    /// </summary>
    public sealed class CacheOptions
    {
        public const string SectionName = "Cache";

        /// <summary>
        /// Top-level prefix for all cache keys generated by this application.
        /// Maps to the application/service name.
        /// Final key format: "{AppPrefix}:{Environment}:{resource}:{id}"
        /// Example:          "caching-api:production:orders:123"
        /// </summary>
        public string AppPrefix { get; init; } = "app";

        /// <summary>
        /// Environment segment injected into every cache key.
        /// WHY: Prevents key collision if staging and production
        /// accidentally share a Redis instance (not recommended, but happens).
        /// </summary>
        public string Environment { get; init; } = "development";

        /// <summary>
        /// Default TTL (Time To Live) for L2 (Redis) cache entries when no explicit TTL is provided.
        /// WHY 5 minutes: Safe default for most read-heavy scenarios.
        /// Override per call for data with different freshness requirements.
        /// </summary>
        public TimeSpan DefaultTtl { get; init; } = TimeSpan.FromMinutes(5);

        /// <summary>
        /// Maximum jitter added to L2 TTL to prevent cache stampede on mass expiry.
        ///
        /// WHAT IS STAMPEDE:
        ///   If 1000 entries all expire at the same second, 1000 requests
        ///   simultaneously hit the database. Jitter spreads expiry across
        ///   a window, smoothing the load.
        ///
        /// HOW: Actual TTL = DefaultTtl + Random(0, MaxJitter)
        /// WHY 30 seconds: Small enough to not affect freshness meaningfully,
        /// large enough to spread expiry across a window.
        /// </summary>
        public TimeSpan MaxJitter { get; init; } = TimeSpan.FromSeconds(30);

        /// <summary>
        /// TTL for L1 (in-process memory) cache entries.
        ///
        /// RULE: Always less than DefaultTtl (L2).
        /// WHY 1 minute: Short enough that memory stays reasonably fresh,
        /// long enough to absorb burst traffic without hitting Redis.
        ///
        /// PITFALL: Do not set this equal to or greater than DefaultTtl.
        /// If L1 and L2 expire at the same time, both miss simultaneously
        /// → stampede hits the DB directly, bypassing Redis entirely.
        /// </summary>
        public TimeSpan MemoryTtl { get; init; } = TimeSpan.FromMinutes(1);

        /// <summary>
        /// Whether cache SET failures should throw or be swallowed.
        /// Default false — cache failure degrades performance, not correctness.
        /// Redis/Memory downtime should not cause 500s.
        ///
        /// WHY FALSE (default):
        ///   Cache is a performance optimization, not a source of truth.
        ///   A failed cache write should be logged and ignored — the request
        ///   succeeds by falling back to the source of truth.
        ///   Only set to true if your design REQUIRES cache consistency.
        ///
        /// PITFALL: Setting this to true makes every cache write a
        /// potential request failure. Redis downtime = API downtime.
        /// </summary>
        public bool ThrowOnCacheFailure { get; init; } = false;
    }
}
