using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace ProductionReadySetup.Contracts.Envelopes
{
    /// <summary>
    /// Universal message wrapper for all events published to RabbitMQ.
    ///
    /// WHY ENVELOPE PATTERN:
    ///   Every message needs metadata beyond just the business payload.
    ///   Metadata enables: idempotency, tracing, versioning, routing,
    ///   debugging, and observability — all without touching the payload.
    ///
    ///   Consumer reads envelope FIRST:
    ///     ← Check MessageId against idempotency store (have I seen this?)
    ///     ← Check Version (can I handle this contract version?)
    ///     ← Push CorrelationId into Serilog LogContext (log correlation)
    ///     ← Route based on MessageType (if using a generic consumer)
    ///   THEN deserializes payload if all checks pass.
    ///
    /// GENERIC TYPE PARAMETER:
    ///   MessageEnvelope{T} where T is the payload type.
    ///   Enforces compile-time type safety — no object/dynamic payload.
    ///   Consumer always knows exactly what T it expects.
    ///
    /// SERIALIZATION:
    ///   System.Text.Json attributes used throughout.
    ///   No Newtonsoft dependency — keeps Contracts project lean.
    ///   JsonPropertyName ensures stable field names regardless of
    ///   C# naming conventions (camelCase in JSON, PascalCase in C#).
    ///
    /// PITFALL: Do not add infrastructure concerns here.
    ///   No RabbitMQ types, no ILogger, no HttpContext.
    ///   This class must remain a pure, serializable DTO.
    /// </summary>
    public sealed class MessageEnvelope<T>
    {
        /// <summary>
        /// Unique identifier for this specific message instance.
        ///
        /// PURPOSE: Idempotency.
        ///   Consumer stores this ID after processing.
        ///   On redelivery, ID already in store → skip processing → ACK.
        ///
        /// FORMAT: UUID v4 — globally unique, no coordination needed.
        /// GENERATED BY: Publisher, once, at publish time. Never by consumer.
        /// </summary>
        [JsonPropertyName("messageId")]
        public string MessageId { get; init; } = Guid.NewGuid().ToString("D");


        /// <summary>
        /// Correlation ID forwarded from the originating HTTP request.
        ///
        /// PURPOSE: Distributed tracing.
        ///   Links this message to the HTTP request that caused it,
        ///   and to all downstream operations (DB writes, other messages).
        ///
        /// HOW IT FLOWS:
        ///   HTTP Request → CorrelationIdMiddleware sets correlationId
        ///   → Controller publishes message with same correlationId
        ///   → Worker reads correlationId → pushes to Serilog LogContext
        ///   → All Worker logs carry same correlationId as the HTTP request
        ///   → One Datadog/Seq query shows the full journey end-to-end.
        /// </summary>
        [JsonPropertyName("correlationId")]
        public string CorrelationId { get; init; } = string.Empty;


        /// <summary>
        /// Fully qualified event type name.
        ///
        /// PURPOSE: Routing + consumer type resolution.
        ///   Generic consumers use this to deserialize the correct payload type.
        ///   Also useful in DLQ inspection — know what the message was without
        ///   deserializing the payload.
        ///
        /// CONVENTION: "{EventName}" — no namespace, no assembly.
        ///   WHY NO NAMESPACE: Namespaces change during refactoring.
        ///   MessageType is a public contract — must be stable across renames.
        ///   Example: "OrderCreated" not "ProductionReadySetup.Contracts.Events.V1.OrderCreatedEvent"
        /// </summary>
        [JsonPropertyName("messageType")]
        public string MessageType { get; init; } = string.Empty;


        /// <summary>
        /// Contract version of the payload.
        ///
        /// PURPOSE: Forward/backward compatibility.
        ///   Consumer checks version BEFORE deserializing payload.
        ///   Unknown version → nack without retry → route to DLQ for inspection.
        ///   Known version → process normally.
        ///
        /// FORMAT: "MAJOR.MINOR"
        ///   MAJOR bump = breaking change → new type in Contracts/Events/V{n}/
        ///   MINOR bump = additive change → same type, new optional fields
        ///
        /// EXAMPLE:
        ///   "1.0" → OrderCreatedEvent V1 (original)
        ///   "1.1" → OrderCreatedEvent V1 with new optional field (backward compatible)
        ///   "2.0" → OrderCreatedEvent V2 (breaking change, separate class)
        /// </summary>
        [JsonPropertyName("version")]
        public string Version { get; init; } = "1.0";


        /// <summary>
        /// UTC timestamp of when the message was published.
        ///
        /// PURPOSE: Debugging, auditing, message age checks.
        ///   Consumer can reject stale messages (published > X hours ago)
        ///   if processing them would cause incorrect business state.
        ///
        /// ALWAYS UTC: Never local time in distributed systems.
        ///   Services may run in different timezones.
        ///   UTC is the only safe common ground.
        /// </summary>
        [JsonPropertyName("timestamp")]
        public DateTimeOffset Timestamp { get; init; } = DateTimeOffset.UtcNow;


        /// <summary>
        /// Logical name of the service that published this message.
        ///
        /// PURPOSE: Debugging and DLQ inspection.
        ///   When a message lands in DLQ, immediately know which service
        ///   published it without querying logs.
        ///
        /// CONVENTION: Match Observability.ServiceName from appsettings.
        ///   Consistent naming across logs and messages.
        /// </summary>
        [JsonPropertyName("source")]
        public string Source { get; init; } = string.Empty;


        /// <summary>
        /// The actual business event data.
        ///
        /// WHY GENERIC:
        ///   Type safety at compile time.
        ///   No casting, no dynamic deserialization.
        ///   Consumer declares exactly what T it expects.
        ///
        /// PITFALL: Keep payload flat and serialization-friendly.
        ///   Avoid: circular references, polymorphic types without discriminators,
        ///   types with private setters and no [JsonConstructor].
        /// </summary>
        [JsonPropertyName("payload")]
        public T Payload { get; init; } = default!;
    }
}
